# Pandas 라이브러리를 활용한 데이터 수집 및 저장

# 2. 데이터베이스 데이터 수집 및 저장 (Mariadb_Mysql)

### 라이브러리 선언하기

In [ ]:
!pip install mysql-connector-python

Collecting mysql-connector-python
  Downloading mysql_connector_python-9.0.0-cp310-cp310-manylinux_2_17_x86_64.whl.metadata (2.0 kB)
Downloading mysql_connector_python-9.0.0-cp310-cp310-manylinux_2_17_x86_64.whl (19.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.3/19.3 MB 33.6 MB/s eta 0:00:00
Installing collected packages: mysql-connector-python
Successfully installed mysql-connector-python-9.0.0

In [ ]:
# Pandas 패키지 불러오기
import pandas as pd
from sqlalchemy import create_engine, inspect

In [ ]:
# # 구글드라이브 연동
# from google.colab import drive
# drive.mount("/content/gdrive")

### 1. 파일 데이터 불러오기

In [ ]:
# CSV 파일을 읽어 Data Frame 변수에 저장하기
selloutDataLocalUrl = "../dataset/kopo_product_volume.csv"
selloutDataGitUrl = "https://raw.githubusercontent.com/hyokwan/python-lecture/master/dataset/kopo_product_volume.csv"
selloutData = pd.read_csv(selloutDataGitUrl)
selloutData.head()

  REGIONID PRODUCTGROUP  YEARWEEK  VOLUME
0      A01       ST0001    201415  810144
1      A01       ST0002    201415  128999
2      A01       ST0001    201418  671464
3      A01       ST0002    201418  134467
4      A01       ST0001    201413  470040

### 2. MySQL에 데이터프레임 저장

In [ ]:
# MySQL 데이터베이스 연결 정보 설정
user = 'kopo'
password = 'kopo'
host = '127.0.0.1'
port = '3306'
database = 'kopodb'

# MySQL 데이터베이스 연결 정보 설정 (클라우드)
user = 'hkcode'
password = 'hkcodemariadb'
host = '139.150.80.119'
port = '3306'
database = 'hkcodedb'

# SQLAlchemy 엔진 생성
engine = create_engine(f'mysql+mysqlconnector://{user}:{password}@{host}:{port}/{database}')

# 데이터프레임을 MySQL 데이터베이스의 테이블에 저장
table_name = 'kopo_product_volume_20240726'.upper()
selloutData.to_sql(name=table_name, con=engine, if_exists='replace', index=False)

265

In [ ]:
# MySQL 데이터베이스 연결 정보 설정 (ngrok)
user = 'kopo'
password = 'kopo'
host = '0.tcp.jp.ngrok.io'
port = '11169'
database = 'kodb'


# SQLAlchemy 엔진 생성
engine = create_engine(f'mysql+mysqlconnector://{user}:{password}@{host}:{port}/{database}')

# 데이터프레임을 MySQL 데이터베이스의 테이블에 저장
table_name = 'kopo_product_volume_ngrok'
selloutData.to_sql(name=table_name, con=engine, if_exists='replace', index=False)

DatabaseError: (mysql.connector.errors.DatabaseError) 2003 (HY000): Can't connect to MySQL server on '0.tcp.jp.ngrok.io:11169' (111)
(Background on this error at: https://sqlalche.me/e/20/4xp6)

### 3. MySQL 내 데이터 조회

In [ ]:
# 테이블 목록 조회
inspector = inspect(engine)

tables = inspector.get_table_names()
tables

# 타겟 테이블 조회
sqlSelect = """
SELECT *
FROM kopo_product_volume"""

selloutDf = pd.read_sql_query(sqlSelect, con=engine)
selloutDf.head()

  REGIONID PRODUCTGROUP  YEARWEEK  VOLUME
0      A01       ST0001    201415  810144
1      A01       ST0002    201415  128999
2      A01       ST0001    201418  671464
3      A01       ST0002    201418  134467
4      A01       ST0001    201413  470040

### [실습] local mysql 데이터를 클라우드 mysql에 저장하세요
customerdata -> customerdata_홍길동

In [ ]:
# PANDAS 패키지 불러오기
import pandas as pd
import pymysql
from sqlalchemy import create_engine

# DB 커넥션 열기
pg_my_engine = create_engine('postgresql://postgres:postgres@127.0.0.1:5432/postgres')
oracle_com_engine = create_engine('oracle+cx_oracle://kopo:kopo@127.0.0.1:1521/xe')

# DB 테이블을 읽어 Data Frame 변수에 저장하기
selloutData = pd.read_sql_query('SELECT * FROM kopo_product_volume', oracle_com_engine)

selloutData.head()

  regionid productgroup yearweek  volume
0      A01       ST0002   201512  151750
1      A01       ST0001   201520  645626
2      A01       ST0002   201520  125863
3      A01       ST0001   201515  810144
4      A01       ST0002   201515  128999